### ISSUE TITLE
Define API

### ISSUE THREAD

**Issue by Bundologus** [Bundologus/ELTE_fullstack_2022#9]

**Comment by nxnmoo** [comment]
Az use_case_diagram esetén:
A Business owner és a Guest mellett egy harmadik nem-admin felhasználótípus mintha egybe lenne mosva a Business owner-rel, ti. a "Create new unit" egy Guest számára, aki csak enni akar egy egységben, sohasem fog kelleni -- ez inkább egy "Business manager" jogköre, akit egy BO jelölhet ki, hogy segítsen az adminisztrációban. Ha ilyen nem szeretnénk, akkor a "Create new unit" case-t át kellene tenni inkább a BO-höz. Pirossal megjelöltem az ábrán.

**Comment by Bundologus** [comment]
Szerintem a "Create new unit" azért tartozik minden user alá, mert gyakorlatilag az különbözteti meg a sima felhasználót a BO-tól, hogy van a neve alatt egy üzlet, és akkor kerül be a BO user groupba, amikor egy admin elfogadja az új hely regisztrációját.

Persze lehet csinálni kétféle regisztrációt, de szerintem user friendlybb, ha nem kell két külön felhasználói fiókot fenntartania annak, aki owner is, és foglalni is szeretne más helyeken.

**Comment by nxnmoo** [comment]
Értem, így végül is logikus. :) Maradjon akkor.
